---
- hosts: all
  become: yes
  tasks:
  - name: Install tree on nodes
    apt:
      name: tree
      update_cache: yes
      state: present
  - name: Create file
    copy:
      src: /home/ansible/demo.txt
      dest: /home/ansible/demo.txt
      owner: root
      group: root
      mode: 0644
    
